[project]
authors = ["Cordero Core <127983572+uwcdc@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "biodiversity-horizons"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
